site_name: Devops Progress

nav:
  - Home: 'index.md'
  - E4Me: 'e4me.md'
  - PAP: 'pap.md'
  - Glossary: 'glossary.md'



site_author: Marcos Cano
site_description: kubernetes (aka k8s) tips, training, guides.


repo_name: Devops Progress
repo_url: https://github-hcs.dxc.com/jcano20/devops-progress.git

edit_uri: "/"

theme:
  name: material
  palette:
    primary: "blue grey"
    accent: 'pink'
  logo: 'assets/images/report.png'
  font:
    text: 'Fira Code'
    code: 'Inconsolata'
  language: 'en'
  include_sidebar: True
  feature:
    tabs: true


extra:
  search:
    language: 'en'

plugins:
  - search


markdown_extensions:
  - footnotes
  - meta
  - toc:
      permalink: true

  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark

  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.smartsymbols
  - admonition

# code blocks
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format




# extra_css:
#     - https://unpkg.com/mermaid/dist/mermaid.css




extra_javascript:
  - https://unpkg.com/mermaid@8.13.3/dist/mermaid.min.js


use_directory_urls: true